[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35072
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -E '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?\.)3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'  temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -E '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?\.)3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'  temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35072
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -E '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?\.)3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'  temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -E '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?\.)3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'  temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -E '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?\.)3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'  temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35072
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -E '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?\.)3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'  temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35072
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -E '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?\.)3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'  temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35072
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -E "free[^[:space:]]+"  temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  ^[^AEIOU]  temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -E '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?\.)3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'  temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35072
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -E '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?\.)3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'  temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35072
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -E '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?\.)3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'  temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35072
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35072
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35072
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  ^[^AEIOU]  temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -E '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?\.)3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'  temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35072
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35072
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35072
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35072
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35072
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35072
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35072
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35072
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -i "Si" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35072
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -E '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?\.)3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'  temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 34304
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 34304
[line:127]-DEBUG-Verify successed!
[line:127]-DEBUG-Verify successed!
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 35584
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -E '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?\.)3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'  temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 34304
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  "a" temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 65280
[line:27]-DEBUG-Failed to execute command: temp/deb_1.out  -o [r][a][n][d]* temp/train1  >> /home/cytmo/Simple_debloater/python_deb/debloater/temp/output_1, ret code is 34304
